PRESET_BASE: minimal
CONFIG_NAME: myposchain

# Time parameters
SECONDS_PER_SLOT: 6
SLOTS_PER_EPOCH: 8
SLOTS_PER_HISTORICAL_ROOT: 64

# Validator parameters
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 1
MIN_GENESIS_TIME: 0

# Fork schedule
GENESIS_FORK_VERSION: 0x00000001
ALTAIR_FORK_EPOCH: 0
BELLATRIX_FORK_EPOCH: 0
CAPELLA_FORK_EPOCH: 0
DENEB_FORK_EPOCH: 0

# Terminal block (The Merge trigger)
TERMINAL_TOTAL_DIFFICULTY: 0
TERMINAL_BLOCK_HASH: 0x0000000000000000000000000000000000000000000000000000000000000000
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 0

# Deposit contract
DEPOSIT_CHAIN_ID: 123451
DEPOSIT_NETWORK_ID: 123451
DEPOSIT_CONTRACT_ADDRESS: 0x0000000000000000000000000000000000000000

